import {
  EmailLength,
  FollowUpDelay,
  Tone,
} from '../schema/campaign.schema';

export class UpdateCampaignSettingsDto {
  tone: Tone;
  emailLength?: EmailLength;
  isFollowUpEnabled?: boolean;
  followUpDelay?: FollowUpDelay;
  senderName?: string;
  signature?: string;
  description?: string;
  /** When true, use subject for all emails; when false, subject is generated by AI per lead. */
  subjectFromUser?: boolean;
  /** Subject line when subjectFromUser is true (entered by user). */
  subject?: string;
}
