import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

/** Follow-up delay in minutes. Use enum for allowed values. */
export enum FollowUpDelay {
  ONE_MINUTE = 'ONE_MINUTE',
  TWO_DAYS = 'TWO_DAYS',
  SEVEN_DAYS = 'SEVEN_DAYS',
  FOURTEEN_DAYS = 'FOURTEEN_DAYS',
  ONE_MONTH = 'ONE_MONTH',
}

export enum Tone {
  FRIENDLY = 'FRIENDLY',
  PROFESSIONAL = 'PROFESSIONAL',
  CASUAL = 'CASUAL',
  DIRECT = 'DIRECT',
}

export enum EmailLength {
  SHORT = 'SHORT',
  MEDIUM = 'MEDIUM',
  LONG = 'LONG',
}

@Schema({ _id: false })
export class CampaignSettings {
  @Prop({ type: String, enum: Tone, default: Tone.PROFESSIONAL })
  tone: Tone;

  @Prop({
    type: String,
    enum: EmailLength,
    default: EmailLength.SHORT,
  })
  emailLength: EmailLength;

  @Prop({ default: false })
  isFollowUpEnabled: boolean;

  @Prop({
    type: String,
    enum: FollowUpDelay,
    default: FollowUpDelay.TWO_DAYS,
  })
  followUpDelay: FollowUpDelay;

  /** Sender name displayed when sending emails to leads (e.g. "Jane Smith <outreach@...>"). */
  @Prop()
  senderName?: string;

  /** Signature appended to emails sent to leads (e.g. "--\nJane Smith"). */
  @Prop()
  signature?: string;

  /** Description of the campaign (e.g. purpose, target audience). */
  @Prop()
  description?: string;

  /** When true, use subject below for all emails; when false, subject is generated by AI per lead. */
  @Prop({ default: false })
  subjectFromUser: boolean;

  /** Subject line when subjectFromUser is true (entered by user). */
  @Prop()
  subject?: string;
}

export const CampaignSettingsSchema =
  SchemaFactory.createForClass(CampaignSettings);

export enum CampaignStatus {
  NOT_STARTED = 'NOT_STARTED',
  EMAIL_DRAFT_GENERATION_STARTED = 'EMAIL_DRAFT_GENERATION_STARTED',
  EMAIL_DRAFT_GENERATION_COMPLETED = 'EMAIL_DRAFT_GENERATION_COMPLETED',
  INITIAL_EMAILS_SEND_STARTED = 'INITIAL_EMAILS_SEND_STARTED',
  INITIAL_EMAILS_SEND_COMPLETED = 'INITIAL_EMAILS_SEND_COMPLETED',
  STOPPED = 'STOPPED',
  COMPLETED = 'COMPLETED',
}

@Schema({ collection: 'Campaign', versionKey: false, timestamps: true })
export class Campaign extends Document {
  declare _id: Types.ObjectId;

  @Prop({ required: true, ref: 'User' })
  userId: Types.ObjectId;

  @Prop({ required: true })
  name: string;

  @Prop({ required: true, default: 0 })
  leadsCount: number;

  @Prop({ type: CampaignSettingsSchema })
  settings: CampaignSettings;

  @Prop({
    type: String,
    enum: CampaignStatus,
    default: CampaignStatus.NOT_STARTED,
  })
  status: CampaignStatus;
}

export const CampaignSchema = SchemaFactory.createForClass(Campaign);

// List campaigns by user, sorted by creation (campaign.service findAllByUser).
CampaignSchema.index({ userId: 1, createdAt: -1 });
