export const CLERK_JWKS_PUBLIC_KEY =
  process.env.ENV === 'prod'
    ? `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA07PE2SN7jA5dGYmWWraY
BflKUHtEOvhfbsC+gFvKpgNurOWgiCL8abbstv0KiwD/OVZAosJqCaKzlhz8EYxj
m/ZSAkOvIMiNlfOGEHeZ4kQGzj1DB9MHEI4gougF77uUHLnnI0lIF/Ivsd0ephns
bJ8Gndsab28br05XkoPORtkg+wy0fb1GosZfJKJC6XbvTRF/lXOiscoCdQZte2n4
bRLqrVzUk9qhSvq1wT8bc2ghfLIA8Ml5guAZJsHw2131J8hYY9kFsUQcuyFc6tCg
ci/8Hlhh2m1xAAlLgZvPLOnrfRD6vZ+RezJuV1Sq/UAJNSoOh4KIoqsvrgW1YwKy
xwIDAQAB
-----END PUBLIC KEY-----
`
    : `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsY1BYfjmVR2vvTq+P5kp
AjDeIyrqqCFRTo+qif+iEYqZFMZoVlNgCByCWvsyRS/TG+oBjdkyACkNIvx8P8S7
uSzfTa0PTDgQ3HHmv2P9lyeDnwOJvhaePtqKluoxzWJIWmbBRa0Tv/387TJLtLOR
Wptogn1z+5gn5VGUsVwQPDXgVH7JQNmYVOgqBcgMNjt5QMGUvokfcWAmJ1qDVQdk
5AUqwt5mJvE909U8qrVXOsr9jLBH2qxWhfkNMIikjaDiTKgppFSk68qu50CvtPfh
BNsMzMyzFhsuPQ4/1Js9nwLDbk+23HlQwPLrKX9M1Qur6NDJhlSbZETyLJpg1kXy
IwIDAQAB
-----END PUBLIC KEY-----
`;
